// <auto-generated />
using System;
using CovidAnalyticsPortal.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CovidAnalyticsPortal.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("CovidAnalyticsPortal.Domain.Entities.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Parameters")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("IX_AuditTrails_Action");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_AuditTrails_CorrelationId");

                    b.HasIndex("TimestampUtc")
                        .HasDatabaseName("IX_AuditTrails_TimestampUtc");

                    b.ToTable("AuditTrails", (string)null);
                });

            modelBuilder.Entity("CovidAnalyticsPortal.Domain.Entities.CovidStatistic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique()
                        .HasDatabaseName("IX_CovidStatistics_Date");

                    b.ToTable("CovidStatistics", (string)null);
                });

            modelBuilder.Entity("CovidAnalyticsPortal.Domain.Entities.StateStatistic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("StateCode");

                    b.HasKey("Id");

                    b.HasIndex("State", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_StateStatistics_State_Date");

                    b.ToTable("StateStatistics", (string)null);
                });

            modelBuilder.Entity("CovidAnalyticsPortal.Domain.Entities.TrendRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ChangePercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ChangeValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EndValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StartValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("StateCode");

                    b.HasKey("Id");

                    b.ToTable("TrendRecords", (string)null);
                });

            modelBuilder.Entity("CovidAnalyticsPortal.Domain.Entities.CovidStatistic", b =>
                {
                    b.OwnsOne("CovidAnalyticsPortal.Domain.ValueObjects.CaseMetrics", "Metrics", b1 =>
                        {
                            b1.Property<Guid>("CovidStatisticId")
                                .HasColumnType("TEXT");

                            b1.Property<long>("ActiveCases")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ActiveCases");

                            b1.Property<long>("CumulativeCases")
                                .HasColumnType("INTEGER")
                                .HasColumnName("CumulativeCases");

                            b1.Property<long>("CumulativeDeaths")
                                .HasColumnType("INTEGER")
                                .HasColumnName("CumulativeDeaths");

                            b1.Property<long>("NewCases")
                                .HasColumnType("INTEGER")
                                .HasColumnName("NewCases");

                            b1.Property<long>("NewDeaths")
                                .HasColumnType("INTEGER")
                                .HasColumnName("NewDeaths");

                            b1.Property<long>("Recovered")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Recovered");

                            b1.HasKey("CovidStatisticId");

                            b1.ToTable("CovidStatistics");

                            b1.WithOwner()
                                .HasForeignKey("CovidStatisticId");
                        });

                    b.Navigation("Metrics")
                        .IsRequired();
                });

            modelBuilder.Entity("CovidAnalyticsPortal.Domain.Entities.StateStatistic", b =>
                {
                    b.OwnsOne("CovidAnalyticsPortal.Domain.ValueObjects.CaseMetrics", "Metrics", b1 =>
                        {
                            b1.Property<Guid>("StateStatisticId")
                                .HasColumnType("TEXT");

                            b1.Property<long>("ActiveCases")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ActiveCases");

                            b1.Property<long>("CumulativeCases")
                                .HasColumnType("INTEGER")
                                .HasColumnName("CumulativeCases");

                            b1.Property<long>("CumulativeDeaths")
                                .HasColumnType("INTEGER")
                                .HasColumnName("CumulativeDeaths");

                            b1.Property<long>("NewCases")
                                .HasColumnType("INTEGER")
                                .HasColumnName("NewCases");

                            b1.Property<long>("NewDeaths")
                                .HasColumnType("INTEGER")
                                .HasColumnName("NewDeaths");

                            b1.Property<long>("Recovered")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Recovered");

                            b1.HasKey("StateStatisticId");

                            b1.ToTable("StateStatistics");

                            b1.WithOwner()
                                .HasForeignKey("StateStatisticId");
                        });

                    b.Navigation("Metrics")
                        .IsRequired();
                });

            modelBuilder.Entity("CovidAnalyticsPortal.Domain.Entities.TrendRecord", b =>
                {
                    b.OwnsOne("CovidAnalyticsPortal.Domain.ValueObjects.DateRange", "Period", b1 =>
                        {
                            b1.Property<Guid>("TrendRecordId")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("End")
                                .HasColumnType("TEXT")
                                .HasColumnName("PeriodEnd");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("TEXT")
                                .HasColumnName("PeriodStart");

                            b1.HasKey("TrendRecordId");

                            b1.ToTable("TrendRecords");

                            b1.WithOwner()
                                .HasForeignKey("TrendRecordId");
                        });

                    b.Navigation("Period")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
